baseURL = 'https://afterthegrind.ai/'
languageCode = 'en-us'
title = 'After the Grind'
theme = 'paper'

[params]
  subtitle = 'Rethinking Work in the Age of AI'
  avatar = ''
  twitter = ''
  github = ''
  disqus = ''
  commentURL = ''

[params.author]
  name = 'Andrew Perkins'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    identifier = 'book'
    name = 'The Book'
    url = 'https://www.amazon.com/dp/B0DV2DP74T'
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
