baseURL = 'https://afterthegrind.ai/'
languageCode = 'en-us'
title = 'After the Grind'
theme = 'paper'
copyright = 'Â© 2026 Andrew Perkins'

[params]
  env = "production"
  description = "Daily essays on AI, the future of work, and what it means to be a professional when the machines can do the tasks. By Andrew Perkins."
  subtitle = 'Rethinking Work in the Age of AI'
  avatar = ''
  linkedin = 'andrew-perkins-291484388'
  rss = true
  twitter = 'andrewwperkins'
  github = ''
  disqus = ''
  commentURL = ''
  name = "Andrew Perkins"
  bio = "Author of *After the Grind*. Chair of Marketing & International Business, WSU."

[params.author]
  name = 'Andrew Perkins'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = 'Topics'
    url = '/tags/'
    weight = 15
  [[menu.main]]
    identifier = 'book'
    name = 'The Book'
    url = '/book/'
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
